{% set name = "msrest" %}
{% set version = "0.6.13" %}
{% set sha256 = "9050fbbb95dd9e8f4008d7227e4dc5662e8b605c89e5621b0dd09ac7f04cf01d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - requests >=2.14
    - requests-oauthlib >=0.5.0
    - isodate >=0.6.0
    - certifi >=2017.4.17
test:
  imports:
    - msrest
    - msrest.authentication
    - msrest.exceptions
    - msrest.pipeline

about:
  home: https://github.com/Azure/msrest-for-python
  license: MIT
  license_family: MIT
  summary: AutoRest swagger generator Python client runtime.

extra:
  recipe-maintainers:
    - ivoflipse
